config/routes.rb
MeterPaid::Application.routes.draw do

  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/about"

  match '/schedules/new' => 'schedules#new'
  match '/tickle' => 'schedules#tickle'
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :schedules, only: [:new, :create, :update, :destroy, :edit]
  
  match '/signup',   to: 'users#new'
  match '/signin',   to: 'sessions#new'
  match '/signout',  to: 'sessions#destroy'
  match '/twilio',   to: 'static_pages#twilio', via: [:get, :post]
  match '/recorded', to: 'static_pages#recorded', via: [:get, :post]
  
  root to: 'static_pages#home'
  

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  attr_accessible :minutes_to_add, :meter, :time
  
  
  validates :minutes_to_add, numericality: { greater_than: 0 }
  validates :meter, presence: true
  validate :at_least_1_min_from_now
  
  before_save :set_status_to_pending
  
  belongs_to :user
  
  default_scope order: "schedules.time"
  
  #status:
  PENDING = 1
  COMPLETED_SUCCESSFULLY = 2
  COMPLETED_WITH_ERROR = 3
  
  private
  
    def at_least_1_min_from_now
      unless time > 1.minutes.from_now
        errors.add(:time, "Must be later than 5 minutes from now")
      end
    end
      
    def set_status_to_pending
      self.status ||= PENDING
    end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation, 
                  :phone, :meter_company_account_pin, :cv2, :remember_token
                  
  has_secure_password
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: {minimum: 6}
  validates :password_confirmation, presence: true, length: {minimum: 6}
  
  before_save :create_remember_token
  
  has_many :schedules
  
  def upcoming_schedules
    self.schedules.where("time > ?", Time.zone.now)
  end
  
  private
  
    def create_remember_token
      self.remember_token ||= SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  include SessionsHelper
  
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController

  include SchedulesHelper

  before_filter :signed_in_user
  skip_before_filter :signed_in_user, only: :tickle

  def new
    @schedule = current_user.schedules.new
    #@schedule.time = 10.minutes.from_now.getlocal
  end

  def create
    @schedule = current_user.schedules.build(params[:schedule])
    if @schedule.save     
      redirect_to root_path
    else
      render 'new'
    end
  end

  def tickle
    Schedule.where("status = #{Schedule::PENDING} and time < ?", Time.zone.now).each do |schedule|
      if (schedule)
        call_meter_company(schedule)
        schedule.status = Schedule::COMPLETED_SUCCESSFULLY
        schedule.save :validate => false
        Rails.logger.info "Scheduled #{schedule.time} minutes on meter ##{schedule.meter} at #{schedule.time}.\n"
      end
    end
    render nothing: true
  end

  def edit
    @schedule = Schedule.find(params[:id])
  end

  def update
    @schedule = Schedule.find(params[:id])
    if (@schedule.update_attributes(params[:schedule]))
      flash[:success] = "Scheduled feed updated."
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    schedule = Schedule.find(params[:id])
    schedule.destroy
    flash[:success] = "Scheduled feed canceled"
    redirect_to root_path
  end
  
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    #don't need to do anything here, it will render /sessions/new.html.erb by default
  end

  def create
    user = User.find_by_email(params[:session][:email])
    if (user && user.authenticate(params[:session][:password]))
      flash[:success] = "Welcome " + user.email
      sign_in user
      redirect_to root_path
    else
      flash[:error] = "Invalid user/password combination"
      render "new"
    end
  end

  def destroy
    sign_out
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

TWI_ML = 
<<-TWILIO_ML
<?xml version='1.0' encoding='utf-8' ?>
<Response>
	<Record transcribe="true" maxLength="60" transcribeCallback="http://meter-paid.herokuapp.com/recorded"/>
	<Hangup />
</Response>
TWILIO_ML

  def home
    @upcoming_schedules = current_user.upcoming_schedules if signed_in?
  end

  def help
  end

  def about
  end
  
  def twilio
    render text: TWI_ML
  end
  
  def recorded
    logger.debug :params.inspect
    render nothing: true
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if (@user.save)
      flash[:success] = "Account created!  Welcome!"
      sign_in @user
      redirect_to root_path
    else
      render "new"
    end
  end
  
  def edit
    @user = User.find_by_id(params[:id])
  end
  
  def update
    @user = User.find_by_id(params[:id])
    if (@user.update_attributes(params[:user]))
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedules_helper.rb
require 'twilio-ruby'

module SchedulesHelper
  
  AccountSid = 'AC019c83da8ef75c162b430e909464f5a4' #MDP account
  AuthToken = '21b3ac20f26865a84b05b9c8d7f54283'
  

  def call_meter_company(schedule)
    
    user = User.find(schedule.user_id)
    
    @client = Twilio::REST::Client.new AccountSid, AuthToken
    @account = @client.account

    @account.calls.create({
      :from => '+14152382438', #MDP account
      :to => '+15106936860',
      :url => 'http://meter-paid.herokuapp.com/twilio',
      :SendDigits => "#{format_extensions_and_delays(schedule, user)}"
    })
    
  end
  
  def format_extensions_and_delays(schedule, user)
    calling_from = user.phone.split("-").join
    pin_number = user.meter_company_account_pin
    credit_cv2 = user.cv2
    
    meter_location = schedule.meter
    minutes_to_add = schedule.minutes_to_add
    
    ed = "*ww" +
            calling_from +
            "ww" + 
            pin_number + 
            "ww" + 
            meter_location + 
            "ww" + 
            minutes_to_add.to_s + 
            "ww" + 
            credit_cv2            
  end
  
  def twilio_ml(schedule_id)
    schedule = Schedule.find(schedule_id)
    user = User.find(schedule.user_id)

    extensions_and_delays = format_extensions_and_delays(schedule, user)

    meter_company_number = "15106936860"

    generated_twiML = 
  <<-TWILIO_ML
  <?xml version="1.0" encoding="UTF-8"?>
  <Response>
      <Dial>
    <Number sendDigits="#{extensions_and_delays}">
    #{meter_company_number}
    </Number>
      </Dial>
  </Response>
  TWILIO_ML

  end
 
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    @current_user = User.find_by_remember_token(cookies[:remember_token])
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
    redirect_to root_path
  end
  
  def signed_in_user
    unless signed_in?
      flash[:error] = 'Please sign in'
      redirect_to root_path 
    end
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<nav>
				<li class='pull-left'><%= image_tag "parkingMeter.jpg", size: "40x50"%></li>
					<ul class="nav pull-right">
					<li><%= link_to "Home",    root_path %></li>
					<li><%= link_to "Help",   '#' %></li>
					<% if signed_in? %>
						<li><%= link_to "Schedule feed", '/schedules/new' %></li>
						<li id="fat_menu" class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								Account <b class="caret"></b>
							</a>
							<ul class="dropdown-menu">
								<li><%= link_to "Profile", current_user %></li>
								<li><%= link_to "Settings", edit_user_path(current_user) %></li>
								<li class="divider"></li>
								<li>
									<%= link_to "Sign out", signout_path, method: "delete" %>
								</li>
							</ul>
						</li>
					<% else %>
						<li><%= link_to "Sign in", signin_path %></li>
					<% end %>
				</ul>
				
			</nav>
		</div>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MeterPaid</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% flash.each do |key, value| %>
		<div class="alert alert-<%= key %>"><%= value %></div>
	<% end %>
	<%= render 'layouts/header' %>
		<div class = "container">
			<div class="row">
				<%= yield %>
			</div>
	</div>
</body>
</html>

app/views/schedules/_schedule_fields.html.erb
<%= f.label :time %>
<%= f.datetime_select :time, default: 10.minutes.from_now, :ampm => true %>

<%= f.label :meter %>
<%= f.text_field :meter %>

<%= f.label :minutes_to_add %>
<%= f.text_field :minutes_to_add %>

app/views/schedules/create.html.erb
<h1>Schedules#create</h1>
<p>Find me in app/views/schedules/create.html.erb</p>

app/views/schedules/destroy.html.erb
<h1>Schedules#destroy</h1>
<p>Find me in app/views/schedules/destroy.html.erb</p>

app/views/schedules/edit.html.erb
<div class='row'>
	<div class = 'span6 offset3'>

		<% if @schedule.errors.any? %>
			<p>There were <%= pluralize(@schedule.errors.count, "error") %></p>
			<ul>
			<% @schedule.errors.full_messages.each do |error| %>
				<li><%= error %></li>
			<% end %>
			</ul>
		<% end %>


		<h1>Schedule Meter Feed</h1>
		<%= form_for(@schedule) do |f| %>
			
			<%= render 'schedule_fields', f: f %>
			<p/><p/>
			<%= f.submit "Save", method: 'put'%>
	
		<% end %>
	</div>
</div>

app/views/schedules/index.html.erb
<h1>Upcoming Schedules</h1>
<% @upcoming_schedules.each do |schedule| %>

	<table>
		<tr>
			<td>Scheduled for:</td>  <td><%= schedule.time %></td>
		</tr>
		<tr>
			<td>Meter number</td>  <td><%= schedule.meter %></td>
		</tr>
		<tr>
			<td>Amount:</td>  <td><%= schedule.amount %></td>
		</tr>
	</table>
<% end %>

app/views/schedules/new.html.erb
<div class='row'>
	<div class = 'span6 offset3'>

		<% if @schedule.errors.any? %>
			<p>There were <%= pluralize(@schedule.errors.count, "error") %></p>
			<ul>
			<% @schedule.errors.full_messages.each do |error| %>
				<li><%= error %></li>
			<% end %>
			</ul>
		<% end %>


		<h1>Schedule Meter Feed</h1>
		<%= form_for(@schedule) do |f| %>
	
			<%= render 'schedule_fields', f: f %>
			<p/><p/>
			<%= f.submit "Schedule"%>
	
		<% end %>
	</div>
</div>

app/views/schedules/show.html.erb
hello world

app/views/schedules/update.html.erb
<h1>Schedules#update</h1>
<p>Find me in app/views/schedules/update.html.erb</p>

app/views/static_pages/_feed.html.erb
<table>
	<tr><td colspan="2">- - - - - - - - - - - -</td></tr>
	<tr>
		<td>Scheduled for:</td>  <td><%= schedule.time %></td>
	</tr>
	<tr>
		<td colspan='2'>
			<%= "(about #{distance_of_time_in_words_to_now(schedule.time)} from now)" %>
		</td>
	</tr>
	<tr>
		<td>Meter number:</td>  <td><%= schedule.meter %></td>
	</tr>
	<tr>
		<td>Minutes:</td>  <td><%= schedule.minutes_to_add %></td>
	</tr>
	<tr>
		<td >
			<%= link_to "change", "/schedules/#{schedule.id}/edit"%>
		</td>
		<td >
			<%= link_to "cancel", "/schedules/#{schedule.id}", 
						method: 'delete', confirm: "You sure?"%>
		</td>
	</tr>
	
</table>

app/views/static_pages/_schedule_list.html.erb
<% if upcoming_schedules.any? %>
	<h2>Scheduled Meter Feeds</h2>
	<% upcoming_schedules.each do |schedule| %>
		<%= render 'feed', schedule: schedule %>
	<% end %>
	<p></p>
	<%= link_to "Schedule another", "/schedules/new", class: "btn center"%>
<% else %>
	<h2>No Upcoming Scheduled Meter Feeds</h2>
	<p></p>
	<%= link_to "Schedule a meter feed", "/schedules/new", class: "btn center"%>
<% end %>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<div class = "container">
<div class = "row">
	<% if signed_in? %>
		<aside class='span4'>
			<h1>Welcome to MeterPaid!</h1>
		</aside>
		<aside class='span7 offset1'>
			<%= render 'schedule_list', upcoming_schedules: @upcoming_schedules %>
		</aside>
	<% else %>
		<div class="center hero-unit">
			<h1>Welcome to MeterPaid!</h1>
			<h3>Feed the parking meter while you sleep.</h3>
			<%= link_to "New user? Sign up!", signup_path, class: "btn btn-large btn-primary" %>

		</div>
	<% end %>
</div>
</div>

app/views/users/_user_fields.html.erb
<% if @user.errors.any? %>
	<p>There were <%= pluralize(@user.errors.count, "error") %></p>
	<ul>
	<% @user.errors.full_messages.each do |error| %>
		<li><%= error %></li>
	<% end %>
	</ul>
<% end %>

<%= f.label :email %>
<%= f.text_field :email %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>

<%= f.label :phone %>
<%= f.text_field :phone %>

<%= f.label :meter_company_account_pin %>
<%= f.text_field :meter_company_account_pin %>

<%= f.label :cv2 %>
<%= f.text_field :cv2 %>
	

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<h1><%= "Update your profile"%></h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>

			<%= render 'user_fields', f: f %>

			<%= f.submit "Save changes" %>
	
		<% end %>
	</div>
</div>

app/views/users/new.html.erb
<div class='span6 offset3'>
<h1>Sign Up</h1>

<%= form_for(@user) do |f| %>

	<%= render 'user_fields', f: f%>
	
	<%= f.submit "Sign me up!" %>

<% end %>

</div>
	

app/views/users/show.html.erb
<div class = 'row'>
	<div class = "span3 offset4">
		<h1>Profile for <%= @user.email %></h1>
		
		<p>Phone: <%= @user.phone %></p>
		<p>Meter company pin: <%= @user.meter_company_account_pin %></p>
		<p>CC CV2: <%= @user.cv2 %></p>
	</div>
</div>